ISOLATES = [i for i in open("/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/isolates.txt").read().split('\n') if len(i) >0]

rule all:
    input:
        expand("/home/mahmadi/tb_seqs/seq_simulation/amplicons/alignment_approach/primer_V2/{isolate}",isolate = ISOLATES)
rule create_amplicon:
    input:
        genome="/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/{isolate}/{isolate}.fna",
        primer="/home/mahmadi/tb_seqs/primers/primer_v2.fastq"
    output:
        directory("/home/mahmadi/tb_seqs/seq_simulation/amplicons/alignment_approach/primer_V2/{isolate}")
    conda:
        "swampy"
    shell:
        """python /home/mahmadi/git_repos/simulate_reads/src/create_amplicons/alignment_based/make_amplicons_alignment_based.py\
         -g {input.genome} -o {output} -p {input.primer} --verbose VERBOSE"""