ISOLATES = [i for i in open("/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/isolates.txt").read().split('\n') if len(i) >0]

rule all:
    input:
        expand("/home/mahmadi/tb_seqs/seq_simulation/amplicons/alignment_approach/primer_V2/{isolate}/{isolate}_amplicon_lengths2.csv",isolate = ISOLATES)
rule create_amplicon:
    input:
        directory("/home/mahmadi/tb_seqs/seq_simulation/amplicons/alignment_approach/primer_V2/{isolate}/"),
    output:
        "/home/mahmadi/tb_seqs/seq_simulation/amplicons/alignment_approach/primer_V2/{isolate}/{isolate}_amplicon_lengths2.csv"
    conda:
        "swampy"
    shell:
        """python /home/mahmadi/git_repos/simulate_reads/src/primer_related_scripts/primer_quality_assessment/primer_assessment.py\
        {input} {output}"""




























