ISOLATES = [i for i in open("/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/isolates.txt").read().split('\n') if len(i) >0]

rule all:
    input:
        expand("/home/mahmadi/tb_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/amplicons",isolate = ISOLATES),
        expand("/home/mahmadi/tb_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/amplicons/all_amplicons_filtered.fasta",isolate = ISOLATES),
        expand("/home/mahmadi/measles_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/reads_1.fastq", isolate= ISOLATES),
        expand("/home/mahmadi/measles_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/reads_2.fastq", isolate= ISOLATES)
rule create_amplicon:
    input:
        genome="/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/{isolate}/{isolate}.fna",
        primer="/home/mahmadi/tb_seqs/primers/primer_v3.bed"
    output:
        directory("/home/mahmadi/tb_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/amplicons")
    conda:
        "freyja"
    shell:
        """python ../create_amplicons/pattern_match/create_amplicons.py\
         -g {input.genome} -o {output} -p {input.primer}"""

rule combine_amplicons:
    input:
        directory("/home/mahmadi/tb_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/amplicons")
    output:
        "/home/mahmadi/tb_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/amplicons/all_amplicons.fasta"
    shell:
        """python ../create_amplicons/alignment_based/combine_filter_amplicons/combine_amplicons.py\
         -i {input} -o {output}"""

rule filter_amplicons:
    input:
        "/home/mahmadi/tb_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/amplicons/all_amplicons.fasta",
    output:
        "/home/mahmadi/tb_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/amplicons/all_amplicons_filtered.fasta"
    conda:
        "freyja"
    shell:
        """python ../create_amplicons/alignment_based/combine_filter_amplicons/filter_amplicons.py -i {input} -o {output}"""

rule simulate_reads:
    input:
        "/home/mahmadi/tb_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/amplicons/all_amplicons_filtered.fasta",
    output:
       output1="/home/mahmadi/measles_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/{abundance}/reads_1.fastq",
       output2="/home/mahmadi/measles_seqs/seq_simulation/amplicons/string_match_approach/primer_V3/{isolate}/reverse_complement/{abundance}/reads_2.fastq"
    conda:
        "wgsim"
    shell:
        """wgsim -1 250 -2 250 -r 0.00001 -d 100 -R 0.00001 -X 0 -e 0.00001 -S 100 -N 50000 {input} {output.output1} {output.output2}"""






